version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Sao_Paulo
  pull-request-branch-name:
    separator: "-"
  ignore:
  - dependency-name: bundler
    versions:
    - 2.2.10
    - 2.2.11
    - 2.2.12
    - 2.2.13
    - 2.2.14
    - 2.2.7
    - 2.2.8
    - 2.2.9
  - dependency-name: activesupport
    versions:
    - 5.2.4.5
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: rake
    versions:
    - 13.0.3
  rebase-strategy: disabled
