require: rubocop-performance

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 130

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 20

Metrics/CyclomaticComplexity:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3.0
  DisplayCopNames: true